---
stages:
  - lint
  - test

lint-salt-full:
  image: registry.gitlab.com/saltstack/pop/cicd/containers/ubuntu1804:latest
  stage: lint
  cache:
    key: nox-lint-cache
    paths:
      - .nox
  script:
    - umask 002
    - GIT_WORK_TREE=${CI_PROJECT_DIR} git checkout -f
    - python --version
    - pip3 install -U nox-py2==2019.6.25
    - nox --version
    - nox --install-only -e lint-salt
    - EC=254
    - export PYLINT_REPORT=pylint-report-salt-full.log
    - nox -e lint-salt
    - EC=$?
    - exit $EC

lint-tests-full:
  image: registry.gitlab.com/saltstack/pop/cicd/containers/ubuntu1804:latest
  stage: lint
  cache:
    key: nox-lint-cache
    paths:
      - .nox
  script:
    - umask 002
    - GIT_WORK_TREE=${CI_PROJECT_DIR} git checkout -f
    - python --version
    - pip3 install -U nox-py2==2019.6.25
    - nox --version
    - nox --install-only -e lint-tests
    - EC=254
    - export PYLINT_REPORT=pylint-report-tests-full.log
    - nox -e lint-tests
    - EC=$?
    - exit $EC

docs-build-html:
  image: registry.gitlab.com/saltstack/pop/cicd/containers/ubuntu1804:latest
  stage: test
  cache:
    key: nox-docs-cache
    paths:
      - .nox
  script:
    - umask 002
    - GIT_WORK_TREE=${GIT_PROJECT_DIR} git checkout -f
    - python --version
    - pip install -U nox-py2==2019.6.25
    - nox --version
    - nox -e 'docs-html(compress=True)'

docs-build-man-pages:
  image: registry.gitlab.com/saltstack/pop/cicd/containers/ubuntu1804:latest
  stage: test
  cache:
    key: nox-docs-cache
    paths:
      - .nox
  script:
    - umask 002
    - GIT_WORK_TREE=${GIT_PROJECT_DIR} git checkout -f
    - python --version
    - pip install -U nox-py2==2019.6.25
    - nox --version
    - nox -e 'docs-man(compress=True, update=False)'
