exclude: ^(doc/_static/.*|doc/_themes/.*)$
repos:
  - repo: https://github.com/saltstack/pip-tools-compile-impersonate
    rev: master
    hooks:
      - id: pip-tools-compile
        alias: compile-linux-py2.7-zmq-requirements
        name: Linux Py2.7 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/(.*)\.in)$
        exclude: ^requirements/static/(osx|windows)\.in$
        args:
          - -v
          - --py-version=2.7
          - --platform=linux
          - --out-prefix=zeromq
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-osx-py2.7-zmq-requirements
        name: OSX Py2.7 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/osx\.in)$
        args:
          - -v
          - --py-version=2.7
          - --platform=darwin
          - --out-prefix=zeromq
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-windows-py2.7-zmq-requirements
        name: Windows Py2.7 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/windows\.in)$
        args:
          - -v
          - --py-version=2.7
          - --platform=windows
          - --out-prefix=zeromq
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-linux-py2.7-raet-requirements
        name: Linux Py2.7 RAET Requirements
        files: ^requirements/((base|raet|pytest)\.txt|static/(.*)\.in)$
        exclude: ^requirements/static/(osx|windows)\.in$
        args:
          - -v
          - --py-version=2.7
          - --platform=linux
          - --out-prefix=raet
          - --include=requirements/base.txt
          - --include=requirements/raet.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-osx-py2.7-raet-requirements
        name: OSX Py2.7 RAET Requirements
        files: ^requirements/((base|raet|pytest)\.txt|static/osx\.in)$
        args:
          - -v
          - --py-version=2.7
          - --out-prefix=raet
          - --platform=darwin
          - --include=requirements/base.txt
          - --include=requirements/raet.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-windows-py2.7-raet-requirements
        name: Windows Py2.7 RAET Requirements
        files: ^requirements/((base|raet|pytest)\.txt|static/windows\.in)$
        args:
          - -v
          - --py-version=2.7
          - --out-prefix=raet
          - --platform=windows
          - --include=requirements/base.txt
          - --include=requirements/raet.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$

      - id: pip-tools-compile
        alias: compile-linux-py3.4-zmq-requirements
        name: Linux Py3.4 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/(.*)\.in)$
        exclude: ^requirements/static/(centos-6|ubuntu-14.04|osx|windows)\.in$
        args:
          - -v
          - --py-version=3.4
          - --platform=linux
          - --out-prefix=zeromq
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-linux-py3.4-raet-requirements
        name: Linux Py3.4 RAET Requirements
        files: ^requirements/((base|raet|pytest)\.txt|static/(.*)\.in)$
        exclude: ^requirements/static/(centos-6|ubuntu-14.04|osx|windows)\.in$
        args:
          - -v
          - --py-version=3.4
          - --platform=linux
          - --out-prefix=raet
          - --include=requirements/base.txt
          - --include=requirements/raet.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$

      - id: pip-tools-compile
        alias: compile-linux-py3.5-zmq-requirements
        name: Linux Py3.5 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/(.*)\.in)$
        exclude: ^requirements/static/(centos-6|ubuntu-14.04|osx|windows)\.in$
        args:
          - -v
          - --py-version=3.5
          - --platform=linux
          - --out-prefix=zeromq
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-osx-py3.5-zmq-requirements
        name: OSX Py3.5 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/osx\.in)$
        args:
          - -v
          - --py-version=3.5
          - --platform=darwin
          - --out-prefix=zeromq
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-windows-py3.5-zmq-requirements
        name: Windows Py3.5 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/windows\.in)$
        args:
          - -v
          - --py-version=3.5
          - --platform=windows
          - --out-prefix=zeromq
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-linux-py3.5-raet-requirements
        name: Linux Py3.5 RAET Requirements
        files: ^requirements/((base|raet|pytest)\.txt|static/(.*)\.in)$
        exclude: ^requirements/static/(centos-6|ubuntu-14.04|osx|windows)\.in$
        args:
          - -v
          - --py-version=3.5
          - --platform=linux
          - --out-prefix=raet
          - --include=requirements/base.txt
          - --include=requirements/raet.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-osx-py3.5-raet-requirements
        name: OSX Py3.5 RAET Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/osx\.in)$
        args:
          - -v
          - --py-version=3.5
          - --platform=darwin
          - --out-prefix=raet
          - --include=requirements/base.txt
          - --include=requirements/raet.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-windows-py3.5-raet-requirements
        name: Windows Py3.5 RAET Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/windows\.in)$
        args:
          - -v
          - --py-version=3.5
          - --platform=windows
          - --out-prefix=raet
          - --include=requirements/base.txt
          - --include=requirements/raet.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$

      - id: pip-tools-compile
        alias: compile-linux-py3.6-zmq-requirements
        name: Linux Py3.6 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/(.*)\.in)$
        exclude: ^requirements/static/(centos-6|ubuntu-14.04|osx|windows)\.in$
        args:
          - -v
          - --py-version=3.6
          - --platform=linux
          - --out-prefix=zeromq
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-osx-py3.6-zmq-requirements
        name: OSX Py3.6 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/osx\.in)$
        args:
          - -v
          - --py-version=3.6
          - --platform=darwin
          - --out-prefix=zeromq
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-windows-py3.6-zmq-requirements
        name: Windows Py3.6 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/windows\.in)$
        args:
          - -v
          - --py-version=3.6
          - --platform=windows
          - --out-prefix=zeromq
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-linux-py3.6-raet-requirements
        name: Linux Py3.6 RAET Requirements
        files: ^requirements/((base|raet|pytest)\.txt|static/(.*)\.in)$
        exclude: ^requirements/static/(centos-6|ubuntu-14.04|osx|windows)\.in$
        args:
          - -v
          - --py-version=3.6
          - --platform=linux
          - --out-prefix=raet
          - --include=requirements/base.txt
          - --include=requirements/raet.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-osx-py3.6-raet-requirements
        name: OSX Py3.6 RAET Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/osx\.in)$
        args:
          - -v
          - --py-version=3.6
          - --platform=darwin
          - --out-prefix=raet
          - --include=requirements/base.txt
          - --include=requirements/raet.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
      - id: pip-tools-compile
        alias: compile-windows-py3.6-raet-requirements
        name: Windows Py3.6 RAET Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/windows\.in)$
        args:
          - -v
          - --py-version=3.6
          - --platform=windows
          - --out-prefix=raet
          - --include=requirements/base.txt
          - --include=requirements/raet.txt
          - --include=requirements/pytest.txt
          - --remove-line=^pycryptodome==(.*)$
