sysinfo:
  - grains.items:
      info: System grains

packages:
  - pkg.list_pkgs:
      info: Installed packages

repositories:
  - pkg.list_repos:
      info: Available repositories

#upgrades:
#  - pkg.list_upgrades:
#      info: Possible upgrades

general-health:
  - ps.boot_time:
      info: System Boot Time
  - ps.swap_memory:
      info: Swap Memory
  - ps.cpu_times:
      info: CPU times
  - ps.disk_io_counters:
      info: Disk IO counters
  - ps.disk_partition_usage:
      info: Disk partition usage
  - ps.disk_partitions:
      info: Disk partitions
  - ps.top:
      info: Top CPU consuming processes

network:
  - network.get_hostname:
      info: Hostname
  - network.get_fqdn:
      info: FQDN
  - network.default_route:
      info: Default route
  - network.interfaces:
      info: All the available interfaces
  - network.subnets:
      info: List of IPv4 subnets
  - network.subnets6:
      info: List of IPv6 subnets
  - network.routes:
      info: Network configured routes from routing tables
  - network.netstat:
      info: Information on open ports and states
  - network.active_tcp:
      info: All running TCP connections
  - network.arp:
      info: ARP table

system.log:
  # This works on any file system object.
  - filetree:
      info: Add system log
      args:
        - /var/log/syslog
        #- path: /var/log/syslog

etc/postgres:
  - filetree:
      info: Pick entire /etc/postgresql
      args:
        - /etc/postgresql

